###
POST http://localhost:4001/user-api/signup
Content-Type: application/json

{
    "name":"charan",
    "email":"charan@gmail.com",
    "password":"123456"
}

###
POSt http://localhost:4001/user-api/signin
Content-Type: application/json

{
    "email":"userB1@example.com",
    "password":"password123"
}

###
GET http://localhost:4001/user-api/logout

### Board Test
POST http://localhost:4001/board-api/addBoard
Content-Type: application/json

{
    "title":"HomeWork",
    "owner":"69b7ba3eaee7c3f3b3359832"
}

###ListModel Test
POST http://localhost:4001/list-api/addList
Content-Type: application/json

{
    "title":"review",
    "board":"69b7c87124910fd7a0449b69",
    "position":1
}

### Card Test
POST http://localhost:4001/card-api/addCard
Content-Type: application/json

{
    "title":"Maths",
    "description":"Complete the exercises",
    "list":"69b7d40857a3b511aaa4558b",
    "position":1
}

### Get Boards


### Delete Board


### Add members to board


### Get Lists


### Delete List


### Move List



### Get Cards
GET http://localhost:4001/card-api/getCards/

### Delete Card


### Move Card
