###
POST http://localhost:4001/user-api/signup
Content-Type: application/json

{
    "name":"charan",
    "email":"charan@gmail.com",
    "password":"123456"
}

###
GET http://localhost:4001/user-api/signin
Content-Type: application/json

{
    "email":"charan@gmail.com",
    "password":"123456"
}

###
GET http://localhost:4001/user-api/logout/69b7ba3eaee7c3f3b3359832

### Board Test
POST http://localhost:4001/board-api/addBoard
Content-Type: application/json

{
    "title":"HomeWork",
    "owner":"69b7ba3eaee7c3f3b3359832"
}
