<-- DSP ->

###
POST http://localhost:4001/user-api/signup
Content-Type: application/json

{
    "name":"charan",
    "email":"charan@gmail.com",
    "password":"123456"
}

###
POST http://localhost:4001/user-api/signin
Content-Type: application/json

{
    "email":"charan@gmail.com",
    "password":"123456"
}

###
GET http://localhost:4001/user-api/logout

### Board Test
POST http://localhost:4001/board-api/addBoard
Content-Type: application/json

{
    "title":"HomeWork",
    "owner":"69b7ba3eaee7c3f3b3359832"
}

### fetch all boards
GET http://localhost:4001/board-api

### fetch board by id
GET http://localhost:4001/board-api/69b7c87124910fd7a0449b69

### delete board
DELETE http://localhost:4001/board-api/deleteBoard/69b7c86f24910fd7a0449b67

###ListModel Test
POST http://localhost:4001/list-api/addList
Content-Type: application/json

{
    "title":"review",
    "board":"69b7c87124910fd7a0449b69",
    "position":1
}
### deleteList by id
DELETE http://localhost:4001/list-api/deleteList/69b7d40857a3b511aaa4558b

### Card Test
POST http://localhost:4001/card-api/addCard
Content-Type: application/json

{
    "title":"Maths",
    "description":"Complete the exercises",
    "list":"69b7d40857a3b511aaa4558b",
    "position":1
}


--------------------------------------------------------------------------------------------------
<-- Sanath ->

###
POST http://localhost:4001/user-api/signup
Content-Type: application/json

{
    "name":"charan",
    "email":"charan@gmail.com",
    "password":"123456"
}

###
POST http://localhost:4001/user-api/signin
Content-Type: application/json

{
    "email":"charan@gmail.com",
    "password":"123456"
}

###
GET http://localhost:4001/user-api/logout



                                                    <---Board-->
### Board Test
POST http://localhost:4001/board-api/addBoard
Content-Type: application/json

{
    "title":"HomeWork",
    "owner":"69b7ba3eaee7c3f3b3359832"
}

### fetch all boards
GET http://localhost:4001/board-api

### fetch board by id
GET http://localhost:4001/board-api/69b90ef55f4ffc8cecc0ae5c

### delete board
DELETE http://localhost:4001/board-api/deleteBoard/69b90daba331eb0f3e8c9eff

### Add members to board

                                                    <---List-->

###ListModel Test
POST http://localhost:4001/list-api/addList
Content-Type: application/json

{
    "title":"review",
    "board":"69b8edc31a3f075dc425ed8d",
    "position":1
}

### deleteList by id
DELETE http://localhost:4001/list-api/deleteList/69b90eb85f4ffc8cecc0ae56

###Get list by boardID
GET http://localhost:4001/list-api/getLists/69b8edc31a3f075dc425ed8d

###Get list by id
GET http://localhost:4001/list-api/getListById/69b9170809a0fe3d2144bd77

### Move List



                                                    <---Card-->

### Card Test
POST http://localhost:4001/card-api/addCard
Content-Type: application/json

{
    "title":"computers",
    "description":"Complete the program",
    "list":"69b90f0f5f4ffc8cecc0ae63",
    "position":1,
    "dueDate":"2026-03-18"
}

### Get Cards
GET http://localhost:4001/card-api/getCards/69b90f0f5f4ffc8cecc0ae63

###Get card by id
GET http://localhost:4001/card-api/getCardById/69b915209fa05fd5622d9920

###Update card by
PUT http://localhost:4001/card-api/updateCard/69b915209fa05fd5622d9920
Content-Type: application/json

{
    "title":"Maths",
    "description":"Complete Sums",
    "dueDate":"2026-03-18"

}

### Delete Card by id
DELETE http://localhost:4001/card-api/deleteCards/69b914b19fa05fd5622d9919

### Move Card

--------------------------------------------------------------------------------------------------
<-- Manohar ->
